#!/usr/bin/env sh
#YABAI STUFF
#yabairc
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config layout bsp # partioning default to binary. There are 3 different placement, stack, bsp, float.
yabai -m config window_placement second_child # a new window introduced, if it is vertically split, it goes to the right, if the screen is horizontally split, it goes to the bottom.

#screen-padding
yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8

#yabai border color on
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config window_border                on
yabai -m config window_border_placement      inset
yabai -m config window_border_width          2
yabai -m config active_window_border_color   0xff32CD32
yabai -m config normal_window_border_color   0xff505050

#window padding
yabai -m config window_gap 12

#mouse settings
yabai -m config mouse_follows_focus on

yabai -m config mouse_modifier alt
#left click +drag move the window
yabai -m config mouse_action1 move
#right lick +drag resize window
yabai -m config mouse_action2 resize
#drag to center of another window, swap places with that window
yabai -m mouse_drop_action swap

#disabling specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Messages$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Stickies$" sticky=on layer=above manage=off

echo "yabai configuration loaded.."
